name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java 21 compile
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Compile code
        run: mvn -B clean compile --file pom.xml

  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Run unit tests
        run: mvn -B clean test --file pom.xml

  build:
    runs-on: ubuntu-latest
    name: Running build
    needs: compile
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      -
        name: Build with Maven
        run: mvn -B clean package --file pom.xml -Dmaven.test.skip=true
